language: cpp

sudo: true
dist: trusty
osx_image: xcode8

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:samuel-bachmann/boost'
    packages: &base_packages
      - libsqlite3-dev
      - libbotan1.10-dev
      - libz-dev
      - bzip2
      - gcovr
      - cppcheck
      - doxygen
      - lcov
      - libboost-date-time1.60-dev
      - pkg-config
      - libusb-1.0-0-dev
      - libbz2-dev
      - libgnutls-dev

install:
  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      brew update
      brew install botan doxygen gettext lcov gcovr libusb gnutls
      brew link --force gettext
      # Already installed: cmake boost
    else
        git clone https://github.com/randombit/botan.git
        (cd botan;
        git checkout 2.3.0;
        ./configure.py;
        sudo make install)
    fi;

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-5
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - sourceline: 'ppa:samuel-bachmann/boost'
            - ubuntu-toolchain-r-test
          packages:
            - *base_packages
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cd build

  - |
    if [ $TRAVIS_OS_NAME = osx ]; then
      cmake -DCMAKE_BUILD_TYPE=Debug -C ../src/clang.txt ..
    fi;

  - |
    if [ $TRAVIS_OS_NAME = linux ]; then
      cmake -DCMAKE_BUILD_TYPE=Debug ..
    fi;

  - make
  - make test CTEST_OUTPUT_ON_FAILURE=1
