sudo: required

services:
  - docker

install: |
  docker build -t neopg-build-env prov

script: |
  docker run \
    --name neopg-build-env \
    --rm neopg-build-env \
    --volume $TRAVIS_BUILD_DIR:/neopg \
    sh -c "cd neopg/build && git submodule update --init && cmake -DCMAKE_BUILD_TYPE=Debug .. && cmake --build . && make test && make coverage"
